### PR TITLE
Initial view style

### PR DESCRIPTION
**Pull request by buseca**

### CODE REVIEW

**Comment by dbertella** [comment]
image

image

checking the preview of this branch on my laptop with dark theme in mac settings and seeing it like this

**Comment by buseca** [comment]
regression fixed

**Comment by buseca** [comment]
Also added CSS for the scrollbar in the gallery (visible only only on desktop)

**Review by dbertella — APPROVED** [review]

**Comment by dbertella** [comment]
Merging this so you'll not have conflicts

**Pull request merged**
